name: Java CI with Gradle

on: push

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: make gradle wrapper executable
      run: chmod +x ./gradlew
    - name: Build
      run: ./gradlew build
    - name: capture build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Artifacts
        path: |
          build/libs/
